version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/tmp/data/work/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - fuxi-mysql
      - cache

  fuxi-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'fuxi'
      MYSQL_USER: 'shao1234'
      MYSQL_PASSWORD: 'shao1234'
      MYSQL_ROOT_PASSWORD: 'shaoyz1234'
    ports:
      - '6033:3306'
    volumes:
      - "fuxi_data:/var/lib/mysql"

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - "cache:/var/lib/cache"

volumes:
    fuxi_data:
    cache:

